language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm


sudo: false

before_script:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
  - php composer/bin/coveralls -v --exclude-no-stmt
